// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;
using WebApplication1.Models;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230819094045_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Name = "Hyundai"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModelID")
                        .HasColumnType("int");

                    b.Property<decimal>("Power")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelID");

                    b.ToTable("cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            ModelID = 1,
                            Power = 180m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            ModelID = 2,
                            Power = 200m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            ModelID = 3,
                            Power = 190m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            ModelID = 4,
                            Power = 250m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            ModelID = 5,
                            Power = 100m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            ModelID = 6,
                            Power = 180m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            ModelID = 7,
                            Power = 200m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            ModelID = 8,
                            Power = 190m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            ModelID = 9,
                            Power = 250m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            ModelID = 10,
                            Power = 100m,
                            Year = 2022
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandID");

                    b.ToTable("models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandID = 1,
                            IsDeleted = false,
                            Name = "Camry",
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            BrandID = 2,
                            IsDeleted = false,
                            Name = "Escape",
                            Type = "SUV"
                        },
                        new
                        {
                            Id = 3,
                            BrandID = 3,
                            IsDeleted = false,
                            Name = "Accord",
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 4,
                            BrandID = 4,
                            IsDeleted = false,
                            Name = "3 Series",
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = 5,
                            BrandID = 5,
                            IsDeleted = false,
                            Name = "Spark",
                            Type = "Hatch"
                        },
                        new
                        {
                            Id = 6,
                            BrandID = 6,
                            IsDeleted = false,
                            Name = "Altima",
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 7,
                            BrandID = 7,
                            IsDeleted = false,
                            Name = "A4",
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 8,
                            BrandID = 8,
                            IsDeleted = false,
                            Name = "Jetta",
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 9,
                            BrandID = 9,
                            IsDeleted = false,
                            Name = "C-Class",
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 10,
                            BrandID = 10,
                            IsDeleted = false,
                            Name = "i20",
                            Type = "Hatch"
                        },
                        new
                        {
                            Id = 11,
                            BrandID = 1,
                            IsDeleted = false,
                            Name = "RAV4",
                            Type = "SUV"
                        },
                        new
                        {
                            Id = 12,
                            BrandID = 2,
                            IsDeleted = false,
                            Name = "Explorer",
                            Type = "SUV"
                        },
                        new
                        {
                            Id = 13,
                            BrandID = 3,
                            IsDeleted = false,
                            Name = "CR-V",
                            Type = "SUV"
                        },
                        new
                        {
                            Id = 14,
                            BrandID = 4,
                            IsDeleted = false,
                            Name = "4 Series",
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = 15,
                            BrandID = 5,
                            IsDeleted = false,
                            Name = "Malibu",
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 16,
                            BrandID = 6,
                            IsDeleted = false,
                            Name = "Rogue",
                            Type = "SUV"
                        },
                        new
                        {
                            Id = 17,
                            BrandID = 7,
                            IsDeleted = false,
                            Name = "A6",
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 18,
                            BrandID = 8,
                            IsDeleted = false,
                            Name = "Passat",
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 19,
                            BrandID = 9,
                            IsDeleted = false,
                            Name = "GLE-Class",
                            Type = "SUV"
                        },
                        new
                        {
                            Id = 20,
                            BrandID = 10,
                            IsDeleted = false,
                            Name = "Elantra",
                            Type = "Sedan"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Car", b =>
                {
                    b.HasOne("WebApplication1.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("WebApplication1.Models.Model", b =>
                {
                    b.HasOne("WebApplication1.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });
#pragma warning restore 612, 618
        }
    }
}
